import { ProductInterface } from "./pages/Products";
import newArrival1 from '@/assets/newArrival1.png'

export const productArray:ProductInterface[] = [
    {
        id: 1,
        name: "Wireless Headphones",
        quantity: 10,
        price: 299.99,
        description: "High-quality noise-canceling headphones.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 2,
        name: "Smartphone",
        quantity: 20,
        price: 799.99,
        description: "Latest model with an amazing camera.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 3,
        name: "Laptop",
        quantity: 5,
        price: 1299.99,
        description: "Powerful laptop for work and gaming.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 4,
        name: "Running Shoes",
        quantity: 15,
        price: 99.99,
        description: "Comfortable and lightweight running shoes.",
        productUrl: newArrival1,
        category: "Fashion",
        loading: false,
    },
    {
        id: 5,
        name: "Smartwatch",
        quantity: 25,
        price: 199.99,
        description: "Track your fitness and notifications on the go.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 6,
        name: "Gaming Console",
        quantity: 8,
        price: 499.99,
        description: "Next-gen gaming console with stunning graphics.",
        productUrl: newArrival1,
        category: "Gaming",
        loading: false,
    },
    {
        id: 7,
        name: "Mechanical Keyboard",
        quantity: 18,
        price: 129.99,
        description: "Tactile switches for a satisfying typing experience.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 8,
        name: "Bluetooth Speaker",
        quantity: 30,
        price: 49.99,
        description: "Portable speaker with deep bass and crisp sound.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 9,
        name: "Backpack",
        quantity: 22,
        price: 59.99,
        description: "Stylish and spacious backpack for daily use.",
        productUrl: newArrival1,
        category: "Fashion",
        loading: false,
    },
    {
        id: 10,
        name: "Coffee Maker",
        quantity: 12,
        price: 89.99,
        description: "Brew fresh coffee quickly and easily.",
        productUrl: newArrival1,
        category: "Home Appliances",
        loading: false,
    },
    {
        id: 11,
        name: "Wireless Mouse",
        quantity: 15,
        price: 39.99,
        description: "Ergonomic and smooth wireless mouse.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 12,
        name: "LED Monitor",
        quantity: 8,
        price: 249.99,
        description: "27-inch Full HD LED monitor with crisp display.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 13,
        name: "Portable Charger",
        quantity: 20,
        price: 29.99,
        description: "Fast-charging power bank with 10000mAh capacity.",
        productUrl: newArrival1,
        category: "Accessories",
        loading: false,
    },
    {
        id: 14,
        name: "Wireless Earbuds",
        quantity: 25,
        price: 89.99,
        description: "True wireless earbuds with noise cancellation.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 15,
        name: "Smart LED Bulb",
        quantity: 30,
        price: 19.99,
        description: "Control brightness and color with your phone.",
        productUrl: newArrival1,
        category: "Home Appliances",
        loading: false,
    },
    {
        id: 16,
        name: "Yoga Mat",
        quantity: 12,
        price: 24.99,
        description: "Non-slip, thick yoga mat for home workouts.",
        productUrl: newArrival1,
        category: "Fitness",
        loading: false,
    },
    {
        id: 17,
        name: "Desk Lamp",
        quantity: 18,
        price: 34.99,
        description: "Adjustable LED desk lamp with warm lighting.",
        productUrl: newArrival1,
        category: "Home Appliances",
        loading: false,
    },
    {
        id: 18,
        name: "Gaming Chair",
        quantity: 7,
        price: 199.99,
        description: "Ergonomic chair with lumbar support for gaming.",
        productUrl: newArrival1,
        category: "Gaming",
        loading: false,
    },
    {
        id: 19,
        name: "Water Bottle",
        quantity: 40,
        price: 14.99,
        description: "Stainless steel insulated water bottle.",
        productUrl: newArrival1,
        category: "Accessories",
        loading: false,
    },
    {
        id: 20,
        name: "Bluetooth Keyboard",
        quantity: 10,
        price: 59.99,
        description: "Compact and lightweight Bluetooth keyboard.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 21,
        name: "Electric Kettle",
        quantity: 22,
        price: 49.99,
        description: "Fast-boiling electric kettle with auto shut-off.",
        productUrl: newArrival1,
        category: "Home Appliances",
        loading: false,
    },
    {
        id: 22,
        name: "Treadmill",
        quantity: 5,
        price: 899.99,
        description: "High-end treadmill with fitness tracking.",
        productUrl: newArrival1,
        category: "Fitness",
        loading: false,
    },
    {
        id: 23,
        name: "Backlit Keyboard",
        quantity: 15,
        price: 79.99,
        description: "Mechanical keyboard with RGB lighting.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 24,
        name: "HD Webcam",
        quantity: 18,
        price: 69.99,
        description: "1080p HD webcam with built-in microphone.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    },
    {
        id: 25,
        name: "Camping Tent",
        quantity: 8,
        price: 149.99,
        description: "Waterproof camping tent for 4 people.",
        productUrl: newArrival1,
        category: "Outdoor",
        loading: false,
    },
    {
        id: 26,
        name: "Dumbbell Set",
        quantity: 20,
        price: 59.99,
        description: "Adjustable dumbbell set for strength training.",
        productUrl: newArrival1,
        category: "Fitness",
        loading: false,
    },
    {
        id: 27,
        name: "Smart Thermostat",
        quantity: 12,
        price: 199.99,
        description: "Energy-saving smart thermostat for homes.",
        productUrl: newArrival1,
        category: "Home Appliances",
        loading: false,
    },
    {
        id: 28,
        name: "Car Vacuum Cleaner",
        quantity: 25,
        price: 39.99,
        description: "Portable and powerful car vacuum cleaner.",
        productUrl: newArrival1,
        category: "Automotive",
        loading: false,
    },
    {
        id: 29,
        name: "Electric Scooter",
        quantity: 5,
        price: 799.99,
        description: "Eco-friendly electric scooter with long battery life.",
        productUrl: newArrival1,
        category: "Outdoor",
        loading: false,
    },
    {
        id: 30,
        name: "Smart Home Hub",
        quantity: 10,
        price: 249.99,
        description: "Central hub to control all smart devices.",
        productUrl: newArrival1,
        category: "Electronics",
        loading: false,
    }
]